In [ ]:
import numpy as np
import tensorflow as tf


In [ ]:
X = np.array ([[1,2],[2,3]])
X

array([[1, 2],
       [2, 3]])

In [ ]:
Y = tf.Variable([[1,2],[3,4]])
Y

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
type(Y)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [ ]:
C = tf.constant([[1,2],[3,4]])
C

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
Z = tf.zeros((3,3))
Z

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [ ]:
# Creating side by side
np_arr = np.array([[1, 2, 3], [4, 5, 6]])
tf_tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

print("NumPy shape:", np_arr.shape, "dtype:", np_arr.dtype)
print("TF shape:", tf_tensor.shape, "dtype:", tf_tensor.dtype)

NumPy shape: (2, 3) dtype: int64
TF shape: (2, 3) dtype: <dtype: 'int32'>


In [ ]:
# Indexing & Slicing
print("\nIndexing (first row):")
print("NumPy:", np_arr[0])
print("TF:", tf_tensor[0])


Indexing (first row):
NumPy: [1 2 3]
TF: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
# Reshaping
print("\nReshaping to 3x2:")
print("NumPy:\n", np.reshape(np_arr, (3, 2)))
print("TF:\n", tf.reshape(tf_tensor, (3, 2)))


Reshaping to 3x2:
NumPy:
 [[1 2]
 [3 4]
 [5 6]]
TF:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
# Mutability
np_arr[0, 0] = 99  # Allowed
print("\nMutated NumPy:", np_arr[0,0])
# tf_tensor[0, 0] = 99  # Not allowed for tf.constant
tf_var = tf.Variable(tf_tensor)
tf_var[0, 0].assign(99) # Allowed for tf.Variable
print("Mutated TF Variable:", tf_var[0,0].numpy())


Mutated NumPy: 99
Mutated TF Variable: 99


In [ ]:
# 2. tf.Variable
var_tensor = tf.Variable([1, 2, 3])
var_tensor.assign([4, 5, 6])
var_tensor.assign_add([1, 1, 1])
print("\nvar_tensor:\n", var_tensor.numpy())


var_tensor:
 [5 6 7]


In [ ]:
zeros = tf.zeros((2, 3))
ones = tf.ones((2, 2))
print("\nzeros:\n", zeros)
print("ones:\n", ones)


zeros:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
ones:
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
# 5. tf.reshape
flat = tf.reshape(zeros, [-1])
print("\nflattened zeros:", flat)


flattened zeros: tf.Tensor([0. 0. 0. 0. 0. 0.], shape=(6,), dtype=float32)


In [ ]:
# 6. tf.concat
t1 = tf.constant([[1, 2], [3, 4]])
t2 = tf.constant([[5, 6], [7, 8]])
concat_0 = tf.concat([t1, t2], axis=0) # 4x2
concat_1 = tf.concat([t1, t2], axis=1) # 2x4
print("\nconcat axis 0:\n", concat_0)
print("concat axis 1:\n", concat_1)


concat axis 0:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
concat axis 1:
 tf.Tensor(
[[1 2 5 6]
 [3 4 7 8]], shape=(2, 4), dtype=int32)


In [ ]:
# 7. tf.stack
stacked = tf.stack([t1, t2], axis=0) # 2x2x2
print("\nstacked:\n", stacked)


stacked:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


# Mathamatical Funcationhs

In [ ]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print("Addition:\n", tf.add(a, b)) # or a + b
print("\nElement-wise Multiplication:\n", tf.multiply(a, b)) # or a * b

Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)

Element-wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [ ]:
# Matrix Multiplication
mat1 = tf.ones((3, 2))
mat2 = tf.ones((2, 4)) * 2
print("\nMatrix Multiplication (3x2 @ 2x4 = 3x4):\n", tf.matmul(mat1, mat2)) # or mat1 @ mat2

# Reduce functions
print("\nMean overall:", tf.reduce_mean(a))
print("Sum axis=0:", tf.reduce_sum(a, axis=0))


Matrix Multiplication (3x2 @ 2x4 = 3x4):
 tf.Tensor(
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]], shape=(3, 4), dtype=float32)

Mean overall: tf.Tensor(2, shape=(), dtype=int32)
Sum axis=0: tf.Tensor([4 6], shape=(2,), dtype=int32)
